#!/usr/bin/env python3
"""Generate the shared TumoVGM protocol constants from the canonical schema."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA = REPO_ROOT / "protocol" / "protocol-v1.json"
DEFAULT_OUTPUT = REPO_ROOT / "include" / "tumovgm" / "protocol_ids.h"


def _bounded_int(value: object, name: str, minimum: int, maximum: int) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{name} must be an integer")
    if value < minimum or value > maximum:
        raise ValueError(f"{name} must be in {minimum}..{maximum}")
    return value


def _validate_values(
    values: object, name: str, minimum: int, maximum: int
) -> dict[str, int]:
    if not isinstance(values, dict) or not values:
        raise ValueError(f"{name} must be a non-empty object")
    validated: dict[str, int] = {}
    for key, value in values.items():
        if not isinstance(key, str) or not key:
            raise ValueError(f"{name} keys must be non-empty strings")
        validated[key] = _bounded_int(value, f"{name}.{key}", minimum, maximum)
    if len(set(validated.values())) != len(validated):
        raise ValueError(f"{name} values must be unique")
    return validated


def _identifier(value: str) -> str:
    return "".join(part.title() for part in value.lower().split("_"))


def _enum(name: str, prefix: str, values: dict[str, int]) -> list[str]:
    lines = [f"typedef enum {name} {{"]
    for key, value in values.items():
        lines.append(f"    {prefix}{_identifier(key)} = {value},")
    lines.append(f"}} {name};")
    return lines


def render(schema: dict) -> str:
    if schema.get("schema_version") != 1:
        raise ValueError("unsupported schema_version")
    protocol = schema["protocol"]
    magic = protocol["magic_ascii"].encode("ascii")
    if len(magic) != 4:
        raise ValueError("protocol magic must contain exactly four ASCII bytes")
    major = _bounded_int(protocol["major"], "protocol.major", 1, 255)
    minor = _bounded_int(protocol["minor"], "protocol.minor", 0, 255)
    max_payload = _bounded_int(protocol["max_payload"], "protocol.max_payload", 1, 512)
    frame_kinds = _validate_values(schema["frame_kinds"], "frame_kinds", 1, 255)
    frame_flags = _validate_values(schema["frame_flags"], "frame_flags", 1, 128)
    messages = _validate_values(schema["messages"], "messages", 1, 65535)
    errors = _validate_values(schema["errors"], "errors", 1, 65535)
    capabilities = _validate_values(schema["capabilities"], "capabilities", 0, 63)

    lines = [
        "/* Generated by tools/generate_protocol_constants.py. Do not edit. */",
        "#ifndef TUMOVGM_PROTOCOL_IDS_H",
        "#define TUMOVGM_PROTOCOL_IDS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define TUMOVGM_PROTOCOL_MAJOR UINT8_C({major})",
        f"#define TUMOVGM_PROTOCOL_MINOR UINT8_C({minor})",
        f"#define TUMOVGM_PROTOCOL_MAX_PAYLOAD UINT16_C({max_payload})",
    ]
    for index, value in enumerate(magic):
        lines.append(f"#define TUMOVGM_PROTOCOL_MAGIC_{index} UINT8_C(0x{value:02X})")

    lines.extend(["", *_enum("TumovgmFrameKind", "TumovgmFrameKind", frame_kinds)])
    lines.extend(["", *_enum("TumovgmFrameFlag", "TumovgmFrameFlag", frame_flags)])
    lines.extend(["", *_enum("TumovgmMessage", "TumovgmMessage", messages)])
    lines.extend(["", *_enum("TumovgmError", "TumovgmError", errors)])

    lines.extend(["", "typedef enum TumovgmCapabilityBit {"])
    for key, bit in capabilities.items():
        lines.append(f"    TumovgmCapabilityBit{_identifier(key)} = {bit},")
    lines.extend(["} TumovgmCapabilityBit;", "", "#endif"])
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        schema = json.loads(args.schema.read_text(encoding="utf-8"))
        generated = render(schema)
    except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as error:
        print(f"error: invalid protocol schema: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError as error:
            print(f"error: generated header is missing: {error}", file=sys.stderr)
            return 1
        if current != generated:
            print(
                "error: generated protocol header is stale; run "
                "python3 tools/generate_protocol_constants.py",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
